/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddToDo: typeof import('./src/components/AddToDo/AddToDo.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox/Checkbox.vue')['default']
    CustomCheckbox: typeof import('./src/components/CustomCheckbox/CustomCheckbox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputComponent: typeof import('./src/components/InputComponent/InputComponent.vue')['default']
    SVGIcon: typeof import('./src/components/SVGIcon/SVGIcon.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToDoItem: typeof import('./src/components/ToDoItem/ToDoItem.vue')['default']
    ToDosList: typeof import('./src/components/ToDosList/ToDosList.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
